### ISSUE TITLE
cordova-build error

### ISSUE THREAD

**Issue by eticsoft** [fechanique/cordova-plugin-fcm#113]
`1>  * What went wrong:
1>MSBUILD : cordova-build error : Execution failed for task ':mergeDebugResources'.
1>  Execution failed for task ':mergeDebugResources'.
1>MSBUILD : cordova-build error : > [string/google_api_key] ......platforms\android\res\values\strings.xml [string/google_api_key] .......\platforms\android\build\generated\res\google-services\debug\values\values.xml: Error: Duplicate resources
1>  > [string/google_api_key] .........\platforms\android\res\values\strings.xml	[string/google_api_key] .......\platforms\android\build\generated\res\google-services\debug\values\values.xml: Error Duplicate resources
1>`

**Comment by benlooi** [comment]
I have the same error. Did not happen before.

**Comment by benlooi** [comment]
Resolved this error. Apparently I added cordova-plugin-firebase as well as cordova-plugin-fcm. Both add something to the strings and values.xml. I removed cordova-plugin-firebase and it worked well for me.
"cordova plugin list"
"cordova plugin remove cordova-plugin-firebase"

**Comment by PriceFallin** [comment]
I did the same thing but even after removing the cordova-plugin-firebase it's still creating the duplicates. Still looking into why. I'm not showing the cordova-plugin-firebase in my config.xml or via the 'cordova plugin list' command. I even did a 'git stash' to partially reset the code and it's still happening.

**Comment by ourarash** [comment]
I have the same issue. What if you want both 'cordova-plugin-firebase' and  'cordova-plugin-fcm' at the same time?

**Comment by mnitpro** [comment]
Removing firebase plugin is not a solution if you're using a firebase DB for logins in your app. It's not a practical solution, where you have to have both plugins FCM and firebase.

I'd suggest using OneSignal [https://documentation.onesignal.com/docs/ionic-sdk-setup] plugin instead of FCM, to avoid the conflict with firebase.
